# -*- coding: utf-8 -*-
"""訓練資料結合.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZ80MbrIfLubYWvqlD3b1VuEuzSQGL50
"""

from google.colab import drive
import numpy as np
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# 變數設定
# %cd '/content/drive/MyDrive/Happy/新版手勢圖片儲存/垃圾'

data_provider = "男-陳泓宇"
mode_type = "英文"

# 調整手勢數量
hg_num = 0
if (mode_type == "英文"):
  hg_num = 27
elif (mode_type == "數字"):
  hg_num = 11

# 個人手部節點的data存取及結合
for i in range(0, hg_num):

    if (mode_type == "英文"):
      file_name = "file_" + chr(i + 97)
    elif (mode_type == "數字"):
      file_name = "file_" + chr(i + 48)

    if (i == hg_num - 1):
      file_name = "file_change"

    data_file = np.load(f'/content/drive/MyDrive/Happy/新版手勢圖片儲存/{mode_type}/{data_provider}/{file_name}.npz', encoding='bytes')

    # 創建資料
    if (i == 0):
      x_train = data_file['x']
      y_train = data_file['y']

    elif (i != 0):
      x_train = np.concatenate([x_train, data_file['x']])
      y_train = np.concatenate([y_train, data_file['y']])

np.savez(f'file_{data_provider}.npz', x = x_train, y = y_train)

# 變數設定
combine_provider = ['男-巫柏樟', '男-胡允升', '男-陳士聿', '男-陳泓宇', '成年女性-生物老師', '成年女性-物理老師']
node_file_name = 'node_file_2+9+12+13+生物+物理_english'

# 結合不同人手的data
for i in range(len(combine_provider)):
  file_temporary = np.load(f'file_{combine_provider[i]}.npz')

  if (i != 0):
    x_train = np.concatenate([x_train, file_temporary['x']])
    y_train = np.concatenate([y_train, file_temporary['y']])

  elif (i == 0):
    x_train = file_temporary['x']
    y_train = file_temporary['y']

x_train.shape
y_train.shape

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/Happy/新版手勢圖片儲存/{mode_type}'
np.savez(node_file_name, x = x_train, y = y_train)

"""##**巫柏樟**"""

file_a = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_a.npz', encoding='bytes')
file_b = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_b.npz', encoding='bytes')
file_c = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_c.npz', encoding='bytes')
file_d = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_d.npz', encoding='bytes')
file_e = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_e.npz', encoding='bytes')
file_f = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_f.npz', encoding='bytes')
file_g = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_g.npz', encoding='bytes')
file_h = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_h.npz', encoding='bytes')
file_i = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_i.npz', encoding='bytes')
# file_j = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_j.npz', encoding='bytes')
file_k = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_k.npz', encoding='bytes')
file_l = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_l.npz', encoding='bytes')
file_m = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_m.npz', encoding='bytes')
file_n = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_n.npz', encoding='bytes')
file_o = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_o.npz', encoding='bytes')
file_p = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_p.npz', encoding='bytes')
file_q = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_q.npz', encoding='bytes')
file_r = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_r.npz', encoding='bytes')
file_s = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_s.npz', encoding='bytes')
file_t = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_t.npz', encoding='bytes')
file_u = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_u.npz', encoding='bytes')
file_v = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_v.npz', encoding='bytes')
file_w = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_w.npz', encoding='bytes')
file_x = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_x.npz', encoding='bytes')
file_y = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_y.npz', encoding='bytes')
# file_z = np.load('/content/drive/MyDrive/Happy/node_file/巫柏樟/file_z.npz', encoding='bytes')

"""##**胡允升**"""

file_a1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_a.npz', encoding='bytes')
file_b1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_b.npz', encoding='bytes')
file_c1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_c.npz', encoding='bytes')
file_d1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_d.npz', encoding='bytes')
file_e1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_e.npz', encoding='bytes')
file_f1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_f.npz', encoding='bytes')
file_g1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_g.npz', encoding='bytes')
file_h1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_h.npz', encoding='bytes')
file_i1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_i.npz', encoding='bytes')
# file_j1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_j.npz', encoding='bytes')
file_k1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_k.npz', encoding='bytes')
file_l1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_l.npz', encoding='bytes')
file_m1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_m.npz', encoding='bytes')
file_n1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_n.npz', encoding='bytes')
file_o1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_o.npz', encoding='bytes')
file_p1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_p.npz', encoding='bytes')
file_q1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_q.npz', encoding='bytes')
file_r1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_r.npz', encoding='bytes')
file_s1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_s.npz', encoding='bytes')
file_t1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_t.npz', encoding='bytes')
file_u1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_u.npz', encoding='bytes')
file_v1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_v.npz', encoding='bytes')
file_w1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_w.npz', encoding='bytes')
file_x1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_x.npz', encoding='bytes')
file_y1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_y.npz', encoding='bytes')
# file_z1 = np.load('/content/drive/MyDrive/Happy/node_file/胡允升/file_z.npz', encoding='bytes')

"""##**林殷碩**"""

file_a2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_a.npz', encoding='bytes')
file_b2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_b.npz', encoding='bytes')
file_c2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_c.npz', encoding='bytes')
file_d2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_d.npz', encoding='bytes')
file_e2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_e.npz', encoding='bytes')
file_f2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_f.npz', encoding='bytes')
file_g2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_g.npz', encoding='bytes')
file_h2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_h.npz', encoding='bytes')
file_i2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_i.npz', encoding='bytes')
# file_j2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_j.npz', encoding='bytes')
file_k2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_k.npz', encoding='bytes')
file_l2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_l.npz', encoding='bytes')
file_m2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_m.npz', encoding='bytes')
file_n2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_n.npz', encoding='bytes')
file_o2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_o.npz', encoding='bytes')
file_p2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_p.npz', encoding='bytes')
file_q2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_q.npz', encoding='bytes')
file_r2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_r.npz', encoding='bytes')
file_s2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_s.npz', encoding='bytes')
file_t2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_t.npz', encoding='bytes')
file_u2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_u.npz', encoding='bytes')
file_v2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_v.npz', encoding='bytes')
file_w2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_w.npz', encoding='bytes')
file_x2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_x.npz', encoding='bytes')
file_y2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_y.npz', encoding='bytes')
# file_z2 = np.load('/content/drive/MyDrive/Happy/node_file/林殷碩/file_z.npz', encoding='bytes')

"""##**鄭翊廷**
* k要重弄
* a, e, m的判別較弱
"""

file_a3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_a.npz', encoding='bytes')
file_b3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_b.npz', encoding='bytes')
file_c3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_c.npz', encoding='bytes')
file_d3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_d.npz', encoding='bytes')
file_e3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_e.npz', encoding='bytes')
file_f3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_f.npz', encoding='bytes')
file_g3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_g.npz', encoding='bytes')
file_h3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_h.npz', encoding='bytes')
file_i3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_i.npz', encoding='bytes')
# file_j3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_j.npz', encoding='bytes')
file_k3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_k.npz', encoding='bytes')
file_l3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_l.npz', encoding='bytes')
file_m3 = np.load('/content/drive/MyDrive/Happy/node_file/鄭翊廷/file_m.npz', encoding='bytes')

"""##**何奕宏**
* 沒有m
"""

file_a4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_a.npz', encoding='bytes')
file_b4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_b.npz', encoding='bytes')
file_c4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_c.npz', encoding='bytes')
file_d4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_d.npz', encoding='bytes')
file_e4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_e.npz', encoding='bytes')
file_f4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_f.npz', encoding='bytes')
file_g4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_g.npz', encoding='bytes')
file_h4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_h.npz', encoding='bytes')
file_i4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_i.npz', encoding='bytes')
# file_j4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_j.npz', encoding='bytes')
file_k4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_k.npz', encoding='bytes')
file_l4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_l.npz', encoding='bytes')
# file_m4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_m.npz', encoding='bytes')
file_n4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_n.npz', encoding='bytes')
file_o4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_o.npz', encoding='bytes')
file_p4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_p.npz', encoding='bytes')
file_q4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_q.npz', encoding='bytes')
file_r4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_r.npz', encoding='bytes')
file_s4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_s.npz', encoding='bytes')
file_t4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_t.npz', encoding='bytes')
file_u4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_u.npz', encoding='bytes')
file_v4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_v.npz', encoding='bytes')
file_w4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_w.npz', encoding='bytes')
file_x4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_x.npz', encoding='bytes')
file_y4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_y.npz', encoding='bytes')
# file_z4 = np.load('/content/drive/MyDrive/Happy/node_file/何弈宏/file_z.npz', encoding='bytes')

"""##**黃柏霖**"""

file_a5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_a.npz', encoding='bytes')
file_b5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_b.npz', encoding='bytes')
file_c5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_c.npz', encoding='bytes')
file_d5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_d.npz', encoding='bytes')
file_e5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_e.npz', encoding='bytes')
file_f5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_f.npz', encoding='bytes')
file_g5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_g.npz', encoding='bytes')
file_h5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_h.npz', encoding='bytes')
file_i5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_i.npz', encoding='bytes')
# file_j5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_j.npz', encoding='bytes')
file_k5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_k.npz', encoding='bytes')
file_l5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_l.npz', encoding='bytes')
file_m5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_m.npz', encoding='bytes')
file_n5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_n.npz', encoding='bytes')
file_o5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_o.npz', encoding='bytes')
file_p5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_p.npz', encoding='bytes')
file_q5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_q.npz', encoding='bytes')
file_r5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_r.npz', encoding='bytes')
file_s5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_s.npz', encoding='bytes')
file_t5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_t.npz', encoding='bytes')
file_u5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_u.npz', encoding='bytes')
file_v5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_v.npz', encoding='bytes')
file_w5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_w.npz', encoding='bytes')
file_x5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_x.npz', encoding='bytes')
file_y5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_y.npz', encoding='bytes')
# file_z5 = np.load('/content/drive/MyDrive/Happy/node_file/黃柏霖/file_z.npz', encoding='bytes')

"""##**Terry + 鄭又誠**"""

file_a6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_a.npz', encoding='bytes')
file_b6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_b.npz', encoding='bytes')
file_c6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_c.npz', encoding='bytes')
file_d6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_d.npz', encoding='bytes')
file_e6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_e.npz', encoding='bytes')
file_f6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_f.npz', encoding='bytes')
file_g6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_g.npz', encoding='bytes')
file_h6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_h.npz', encoding='bytes')
file_i6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_i.npz', encoding='bytes')
# file_j6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_j.npz', encoding='bytes')
file_k6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_k.npz', encoding='bytes')
file_l6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_l.npz', encoding='bytes')
file_m6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_m.npz', encoding='bytes')
file_n6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_n.npz', encoding='bytes')
file_o6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_o.npz', encoding='bytes')
file_p6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_p.npz', encoding='bytes')
file_q6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_q.npz', encoding='bytes')
file_r6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_r.npz', encoding='bytes')
file_s6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_s.npz', encoding='bytes')
file_t6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_t.npz', encoding='bytes')
file_u6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_u.npz', encoding='bytes')
file_v6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_v.npz', encoding='bytes')
file_w6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_w.npz', encoding='bytes')
file_x6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_x.npz', encoding='bytes')
file_y6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_y.npz', encoding='bytes')
# file_z6 = np.load('/content/drive/MyDrive/Happy/node_file/Terry + 鄭又誠/file_z.npz', encoding='bytes')

"""##**結合**"""

# x_train1_1 = np.concatenate([file_a['x'], file_b['x'], file_c['x'], file_d['x'], file_e['x'], file_f['x'], file_g['x'], file_h['x'], file_i['x']])
# x_train1_2 = np.concatenate([file_k['x'], file_l['x'], file_m['x'], file_n['x'], file_o['x'], file_p['x'], file_q['x'], file_r['x'], file_s['x']])
# x_train1_3 = np.concatenate([file_t['x'], file_u['x'], file_v['x'], file_w['x'], file_x['x'], file_y['x']])
x_train2_1 = np.concatenate([file_a1['x'], file_b1['x'], file_c1['x'], file_d1['x'], file_e1['x'], file_f1['x'], file_g1['x'], file_h1['x'], file_i1['x']])
x_train2_2 = np.concatenate([file_k1['x'], file_l1['x'], file_m1['x'], file_n1['x'], file_o1['x'], file_p1['x'], file_q1['x'], file_r1['x'], file_s1['x']])
x_train2_3 = np.concatenate([file_t1['x'], file_u1['x'], file_v1['x'], file_w1['x'], file_x1['x'], file_y1['x']])
x_train3_1 = np.concatenate([file_a2['x'], file_b2['x'], file_c2['x'], file_d2['x'], file_e2['x'], file_f2['x'], file_g2['x'], file_h2['x'], file_i2['x']])
x_train3_2 = np.concatenate([file_k2['x'], file_l2['x'], file_m2['x'], file_n2['x'], file_o2['x'], file_p2['x'], file_q2['x'], file_r2['x'], file_s2['x']])
x_train3_3 = np.concatenate([file_t2['x'], file_u2['x'], file_v2['x'], file_w2['x'], file_x2['x'], file_y2['x']])
# x_train4_1 = np.concatenate([file_a3['x'], file_b3['x'], file_c3['x'], file_d3['x'], file_e3['x'], file_f3['x'], file_g3['x'], file_h3['x'], file_i3['x']])
# x_train4_2 = np.concatenate([file_k3['x'], file_l3['x'], file_m3['x']])
# x_train5_1 = np.concatenate([file_a4['x'], file_b4['x'], file_c4['x'], file_d4['x'], file_e4['x'], file_f4['x'], file_g4['x'], file_h4['x'], file_i4['x']])
# x_train5_2 = np.concatenate([file_k4['x'], file_l4['x'], file_n4['x'], file_o4['x'], file_p4['x'], file_q4['x'], file_r4['x'], file_s4['x']])
# x_train5_3 = np.concatenate([file_t4['x'], file_u4['x'], file_v4['x'], file_w4['x'], file_x4['x'], file_y4['x']])
# x_train6_1 = np.concatenate([file_a5['x'], file_b5['x'], file_c5['x'], file_d5['x'], file_e5['x'], file_f5['x'], file_g5['x'], file_h5['x'], file_i5['x']])
# x_train6_2 = np.concatenate([file_k5['x'], file_l5['x'], file_m5['x'], file_n5['x'], file_o5['x'], file_p5['x'], file_q5['x'], file_r5['x'], file_s5['x']])
# x_train6_3 = np.concatenate([file_t5['x'], file_u5['x'], file_v5['x'], file_w5['x'], file_x5['x'], file_y5['x']])
# x_train7_1 = np.concatenate([file_a6['x'], file_b6['x'], file_c6['x'], file_d6['x'], file_e6['x'], file_f6['x'], file_g6['x'], file_h6['x'], file_i6['x']])
# x_train7_2 = np.concatenate([file_k6['x'], file_l6['x'], file_m6['x'], file_n6['x'], file_o6['x'], file_p6['x'], file_q6['x'], file_r6['x'], file_s6['x']])
# x_train7_3 = np.concatenate([file_t6['x'], file_u6['x'], file_v6['x'], file_w6['x'], file_x6['x'], file_y6['x']])

x_train = np.concatenate([x_train3_1, x_train3_2, x_train3_3, x_train2_1, x_train2_2, x_train2_3])

x_train.shape

# y_train1_1 = np.concatenate([file_a['y'], file_b['y'], file_c['y'], file_d['y'], file_e['y'], file_f['y'], file_g['y'], file_h['y'], file_i['y']])
# y_train1_2 = np.concatenate([file_k['y'], file_l['y'], file_m['y'], file_n['y'], file_o['y'], file_p['y'], file_q['y'], file_r['y'], file_s['y']])
# y_train1_3 = np.concatenate([file_t['y'], file_u['y'], file_v['y'], file_w['y'], file_y['y'], file_y['y']])
y_train2_1 = np.concatenate([file_a1['y'], file_b1['y'], file_c1['y'], file_d1['y'], file_e1['y'], file_f1['y'], file_g1['y'], file_h1['y'], file_i1['y']])
y_train2_2 = np.concatenate([file_k1['y'], file_l1['y'], file_m1['y'], file_n1['y'], file_o1['y'], file_p1['y'], file_q1['y'], file_r1['y'], file_s1['y']])
y_train2_3 = np.concatenate([file_t1['y'], file_u1['y'], file_v1['y'], file_w1['y'], file_y1['y'], file_y1['y']])
y_train3_1 = np.concatenate([file_a2['y'], file_b2['y'], file_c2['y'], file_d2['y'], file_e2['y'], file_f2['y'], file_g2['y'], file_h2['y'], file_i2['y']])
y_train3_2 = np.concatenate([file_k2['y'], file_l2['y'], file_m2['y'], file_n2['y'], file_o2['y'], file_p2['y'], file_q2['y'], file_r2['y'], file_s2['y']])
y_train3_3 = np.concatenate([file_t2['y'], file_u2['y'], file_v2['y'], file_w2['y'], file_x2['y'], file_y2['y']])
# y_train4_1 = np.concatenate([file_a3['y'], file_b3['y'], file_c3['y'], file_d3['y'], file_e3['y'], file_f3['y'], file_g3['y'], file_h3['y'], file_i3['y']])
# y_train4_2 = np.concatenate([file_k3['y'], file_l3['y'], file_m3['y']])
# y_train5_1 = np.concatenate([file_a4['y'], file_b4['y'], file_c4['y'], file_d4['y'], file_e4['y'], file_f4['y'], file_g4['y'], file_h4['y'], file_i4['y']])
# y_train5_2 = np.concatenate([file_k4['y'], file_l4['y'], file_n4['y'], file_o4['y'], file_p4['y'], file_q4['y'], file_r4['y'], file_s4['y']])
# y_train5_3 = np.concatenate([file_t4['y'], file_u4['y'], file_v4['y'], file_w4['y'], file_x4['y'], file_y4['y']])
# y_train6_1 = np.concatenate([file_a5['y'], file_b5['y'], file_c5['y'], file_d5['y'], file_e5['y'], file_f5['y'], file_g5['y'], file_h5['y'], file_i5['y']])
# y_train6_2 = np.concatenate([file_k5['y'], file_l5['y'], file_m5['y'], file_n5['y'], file_o5['y'], file_p5['y'], file_q5['y'], file_r5['y'], file_s5['y']])
# y_train6_3 = np.concatenate([file_t5['y'], file_u5['y'], file_v5['y'], file_w5['y'], file_y5['y'], file_y5['y']])
# y_train7_1 = np.concatenate([file_a6['y'], file_b6['y'], file_c6['y'], file_d6['y'], file_e6['y'], file_f6['y'], file_g6['y'], file_h6['y'], file_i6['y']])
# y_train7_2 = np.concatenate([file_k6['y'], file_l6['y'], file_m6['y'], file_n6['y'], file_o6['y'], file_p6['y'], file_q6['y'], file_r6['y'], file_s6['y']])
# y_train7_3 = np.concatenate([file_t6['y'], file_u6['y'], file_v6['y'], file_w6['y'], file_y6['y'], file_y6['y']])

y_train = np.concatenate([y_train3_1, y_train3_2, y_train3_3, y_train2_1, y_train2_2, y_train2_3])

y_train.shape

